
-- Добавляем недостающие подарки для всех кейсов с правильными ценами
INSERT OR REPLACE INTO gifts_prices (name, price, created_at, updated_at) VALUES 
('Heart Locket', 1800.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Neko Helmet', 22.22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Toy Bear', 15.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ionic Dryer', 14.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Love Potion', 7.9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Valentine Box', 3.7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Joyful Bundle', 2.48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nail Bracelet', 99.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bonded Ring', 46.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Genie Lamp', 35.56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Swiss Watch', 28.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Signet Ring', 20.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cupid Charm', 8.44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sleigh Bell', 5.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
