
CREATE TABLE pvp_game_results (
id INTEGER PRIMARY KEY AUTOINCREMENT,
game_id INTEGER NOT NULL,
game_number INTEGER NOT NULL,
winner_id TEXT NOT NULL,
winner_data TEXT NOT NULL,
winner_percentage REAL NOT NULL,
total_bet_amount REAL NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
